feat(spcr-settings): unify style with the current Spotify
FlafyDev/spicetify-creator-plugins pull request #8
Opened 2023-07-09 16:43 UTC by SunsetTechuila

before:
![image](https://github.com/FlafyDev/spicetify-creator-plugins/assets/115353812/b8b7af44-91e7-47d3-9c61-04a2ceb14a4e)

after:
![image](https://github.com/FlafyDev/spicetify-creator-plugins/assets/115353812/778db74e-23fd-4e49-9667-49d78bec1f99)

2023-08-13 21:23 UTC, FlafyDev commented on packages/spcr-settings/settingsSection.tsx
> +      pluginSettingsContainer.className = "settingsContainer";
You dropped `settings.module.css` so you removed `styles.settingsContainer`. But why replace it with `"settingsContainer"`? I don't think it does anything.

2023-08-13 21:34 UTC, FlafyDev requested changes
The current types try to _not_ relay on Spotify's classes as much as possible. This is because otherwise every time Spotify would change the settings' class names this plugin would break.

Also, look at the Button's styles. It finds the styles of the buttons in the settings page at runtime (see line 68) thus not having to hardcode Spotify's classes into the code ahead of time.

This PR seems to take a lot of classes from Spotify, which increases its chances to break between updates. Especially by using types with randomly generated strings such as  `Type__TypeElement-sc-goli3j-0`, and `Button-sc-y0gtbx-0` which are present in this PR.

EDIT: sorry, I meant to combine the previous comment and this comment in the same review..

2023-08-13 21:52 UTC, SunsetTechuila commented
> The current types try to not relay on Spotify's classes as much as possible
> This PR seems to take a lot of classes from Spotify, which increases its chances to break between updates

A plugin that provides the ability to integrate your settings into Spotify's ones, should itself be integrated with Spotify as much as possible to provide seamless UX/UI between stock and mods. Because if you don't care about UI/UX unity, why use that plugin? In that case, it's more reasonable to make your own settings window/page/panel according to your preferences and needs (and that's what most devs do).
Using your own classes (especially those generated automatically) completely destroys this paradigm, because when installing any custom theme, user will immediately see where the stock settings end and where the settings added with this plugin begin.
That's my opinion. About these classes being subject to change - these particular ones don't change very often, but I can add them to the css map if that's a worry for you.

2023-08-17 19:02 UTC, SunsetTechuila commented
> such as `Type__TypeElement-sc-goli3j-0`, and `Button-sc-y0gtbx-0`

removed since they are doing nothing

2023-08-17 19:03 UTC, SunsetTechuila commented
works even with `1.2.5.1006.g22820f93` (latest is `1.2.18.999.g9b38fc27`)
![image](https://github.com/FlafyDev/spicetify-creator-plugins/assets/115353812/f99b2a4c-7295-40fd-9b45-cc6098b46809)

2023-08-21 17:41 UTC, merged

2023-08-21 17:42 UTC, FlafyDev commented
Let's hope it'll last. thanks!

2023-08-21 17:52 UTC, SunsetTechuila commented
don't forget to bump version this time :)